name: "Release by Tag"

on:
  push:
    tags:
      - r\d+\.\d+\.\d+
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          lfs: true

      - run: |
          mkdir ./dist

      - uses: natsuneko-laboratory/create-vpmpackage@493657e038d11a1cd960560aaed46074fc2facaa #v1.2.0
        with:
          packages: |
            Packages/com.frou01.gac/package.json
          outputs: |
            dist/gac.zip